variables:
  azureServiceConnectionId: 'BillTestServiceConnection'
  webAppName: 'python-flask-test2'
  vmImageName: 'ubuntu-latest'
  environmentName: 'python-flask-test2'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

jobs:
- job: BuildJob
  pool:
    vmImage: $(vmImageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
  - script: |
      python -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install setup
      pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(projectRoot)
    displayName: "Install requirements"
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(projectRoot)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
